### PR TITLE
Version 0.111.3

### PR DESCRIPTION
**Pull request by Noodlesalat**
Hi! :)
I would like to see hugo v0.110.0 in this docker container. I took the last hugo update ([https://github.com/klakegg/docker-hugo/commit/81b3d62dc8c2915931c22d6992840d9d26c49d23](https://github.com/klakegg/docker-hugo/commit/81b3d62dc8c2915931c22d6992840d9d26c49d23)) as a reference for this pull request. I hope this includes all necessary changes.

Because the last pushed version was v0.107.0 I referenced this release in `doc/changelog/0.110.0.md`.

### CODE REVIEW

**Comment by Tekki** [comment]
Today (March 6, 2023) we are already at v.0.111.2.

**Comment by Noodlesalat** [comment]
I have updates the pull request accordingly.

@klakegg: Can you please take a look?

**Comment by Tealk** [comment]
This would be nice if the Hugo update v0.111.3 could be implemented

**Comment by klakegg** [comment]
Version 0.111.3 is out.

**Pull request closed without merging**
